/********************************************************************************
** Form generated from reading UI file 'mainWindow.ui'
**
** Created by: Qt User Interface Compiler version 5.14.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QGridLayout>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMdiArea>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *actionNew;
    QAction *actionOpen;
    QAction *actionSave;
    QAction *actionClose;
    QAction *actionSaveAs;
    QAction *actionChinese;
    QAction *actionEnglish;
    QAction *actionImportMesh;
    QAction *actionImportGeometry;
    QAction *actionWorkingDir;
    QAction *actionSolve;
    QAction *actionSolver_Manager;
    QAction *actionViewXPlus;
    QAction *actionViewXMinus;
    QAction *actionViewYPlus;
    QAction *actionViewYMinus;
    QAction *actionViewZPlus;
    QAction *actionViewZMinus;
    QAction *actionFitView;
    QAction *actionSelectOff;
    QAction *actionSelectMeshNode;
    QAction *actionSelectMeshCell;
    QAction *actionSolve_Options;
    QAction *actionGraph_Options;
    QAction *actionSurfaceMesh;
    QAction *actionSolidMesh;
    QAction *actionExportMesh;
    QAction *actionUser_Manual;
    QAction *actionAbout;
    QAction *actionDisplayNode;
    QAction *actionDisplayWireFrame;
    QAction *actionDisplaySurface;
    QAction *actionDisplaySurfaceEdge;
    QAction *actionCreate_Set;
    QAction *action2DPlot;
    QAction *action3DGraph;
    QAction *actionSave_Script;
    QAction *actionExecute_Script;
    QAction *actionGenMesh;
    QAction *actionSave_Picture;
    QAction *actionBoxMeshNode;
    QAction *actionBoxMeshCell;
    QAction *actionStart_Page;
    QAction *actionPre_Window;
    QAction *actionChecking;
    QAction *actionCreateBox;
    QAction *actionCreateCylinder;
    QAction *actionCreaterSphere;
    QAction *actionChamfer;
    QAction *actionFillet;
    QAction *actionBoolCut;
    QAction *actionBoolFause;
    QAction *actionBoolCommon;
    QAction *actionUndo;
    QAction *actionRedo;
    QAction *actionExportGeometry;
    QAction *actionCreaterCone;
    QAction *actionMirrorFeature;
    QAction *actionVariable_Fillet;
    QAction *actionExtrude;
    QAction *actionCreate_Point;
    QAction *actionCreate_Line;
    QAction *actionCreate_Face;
    QAction *actionMoveFeature;
    QAction *actionRotateFeature;
    QAction *actionRevol;
    QAction *actionLoft;
    QAction *actionCreateDatumPlane;
    QAction *actionDrawLine;
    QAction *actionDrawRectangle;
    QAction *actionDrawCircle;
    QAction *actionCreate_Sketch;
    QAction *actionDrawArc;
    QAction *actionDrawPolyline;
    QAction *actionMakeMatrix;
    QAction *actionSweep;
    QAction *actionDrawSpline;
    QAction *actionDisplayPoint;
    QAction *actionDisplayCurve;
    QAction *actionDisplayFace;
    QAction *actionSelectPoint;
    QAction *actionSelectCurve;
    QAction *actionSelectFace;
    QAction *actionSelectGeometryBody;
    QAction *actionPluginManager;
    QAction *actionUser_Guidance;
    QAction *actionMeasure_Distance;
    QAction *actionMeasure;
    QAction *actionGeoSplitter;
    QAction *actionCreateGeoComponent;
    QAction *actionFluidMesh;
    QAction *actionFilterMesh;
    QAction *actionFillHole;
    QAction *actionRemoveSurface;
    QAction *actionFillGap;
    QAction *actionVTKTranslation;
    QWidget *centralwidget;
    QGridLayout *gridLayout;
    QMdiArea *mdiArea;
    QStatusBar *statusbar;
    QToolBar *FileToolBar;
    QToolBar *SolveToolBar;
    QToolBar *ViewToolBar;
    QToolBar *SelectToolBar;
    QToolBar *MeshToolBar;
    QToolBar *DisplayToolBar;
    QToolBar *SetToolBar;
    QToolBar *RedoToolBar;
    QToolBar *StartSketchToolBar;
    QToolBar *GeomertryFeatureToolBar;
    QToolBar *ChamferToolBar;
    QToolBar *BoolToolBar;
    QToolBar *FeatureOpertionToolBar;
    QToolBar *SketchToolBar;
    QMenuBar *menubar;
    QMenu *menuFile;
    QMenu *menuView;
    QMenu *menuHelp;
    QMenu *menuSolve;
    QMenu *menuSettings;
    QMenu *menuLanguage;
    QMenu *menuMesher;
    QMenu *menuView_2;
    QMenu *menuSelect;
    QMenu *menuPost;
    QMenu *menuWindows;
    QMenu *menuGeometry;
    QMenu *menuFeature_Modeling;
    QMenu *menuView_3;
    QMenu *menuFeature_Operation;
    QMenu *menuSelect_2;
    QMenu *menuSketch;
    QMenu *menuPlugins;
    QToolBar *MeasureToolBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->setEnabled(true);
        MainWindow->resize(1678, 921);
        actionNew = new QAction(MainWindow);
        actionNew->setObjectName(QString::fromUtf8("actionNew"));
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/QUI/icon/createNew.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionNew->setIcon(icon);
        actionOpen = new QAction(MainWindow);
        actionOpen->setObjectName(QString::fromUtf8("actionOpen"));
        QIcon icon1;
        icon1.addFile(QString::fromUtf8(":/QUI/icon/open.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionOpen->setIcon(icon1);
        actionSave = new QAction(MainWindow);
        actionSave->setObjectName(QString::fromUtf8("actionSave"));
        actionSave->setEnabled(false);
        QIcon icon2;
        icon2.addFile(QString::fromUtf8(":/QUI/icon/save.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionSave->setIcon(icon2);
        actionClose = new QAction(MainWindow);
        actionClose->setObjectName(QString::fromUtf8("actionClose"));
        QIcon icon3;
        icon3.addFile(QString::fromUtf8(":/QUI/icon/stop.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionClose->setIcon(icon3);
        actionSaveAs = new QAction(MainWindow);
        actionSaveAs->setObjectName(QString::fromUtf8("actionSaveAs"));
        actionSaveAs->setEnabled(false);
        QIcon icon4;
        icon4.addFile(QString::fromUtf8(":/QUI/icon/saveAs.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionSaveAs->setIcon(icon4);
        actionChinese = new QAction(MainWindow);
        actionChinese->setObjectName(QString::fromUtf8("actionChinese"));
        QIcon icon5;
        icon5.addFile(QString::fromUtf8(":/QUI/icon/chinese_language.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionChinese->setIcon(icon5);
        actionEnglish = new QAction(MainWindow);
        actionEnglish->setObjectName(QString::fromUtf8("actionEnglish"));
        QIcon icon6;
        icon6.addFile(QString::fromUtf8(":/QUI/icon/english_language.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionEnglish->setIcon(icon6);
        actionImportMesh = new QAction(MainWindow);
        actionImportMesh->setObjectName(QString::fromUtf8("actionImportMesh"));
        QIcon icon7;
        icon7.addFile(QString::fromUtf8(":/QUI/icon/importMesh.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionImportMesh->setIcon(icon7);
        actionImportGeometry = new QAction(MainWindow);
        actionImportGeometry->setObjectName(QString::fromUtf8("actionImportGeometry"));
        QIcon icon8;
        icon8.addFile(QString::fromUtf8(":/QUI/icon/importGeometry.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionImportGeometry->setIcon(icon8);
        actionWorkingDir = new QAction(MainWindow);
        actionWorkingDir->setObjectName(QString::fromUtf8("actionWorkingDir"));
        actionWorkingDir->setIcon(icon1);
        actionSolve = new QAction(MainWindow);
        actionSolve->setObjectName(QString::fromUtf8("actionSolve"));
        actionSolve->setEnabled(false);
        QIcon icon9;
        icon9.addFile(QString::fromUtf8(":/QUI/icon/solve.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionSolve->setIcon(icon9);
        actionSolver_Manager = new QAction(MainWindow);
        actionSolver_Manager->setObjectName(QString::fromUtf8("actionSolver_Manager"));
        QIcon icon10;
        icon10.addFile(QString::fromUtf8(":/QUI/icon/setting.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionSolver_Manager->setIcon(icon10);
        actionViewXPlus = new QAction(MainWindow);
        actionViewXPlus->setObjectName(QString::fromUtf8("actionViewXPlus"));
        actionViewXPlus->setEnabled(false);
        QIcon icon11;
        icon11.addFile(QString::fromUtf8(":/QUI/icon/xPlus.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionViewXPlus->setIcon(icon11);
        actionViewXMinus = new QAction(MainWindow);
        actionViewXMinus->setObjectName(QString::fromUtf8("actionViewXMinus"));
        actionViewXMinus->setEnabled(false);
        QIcon icon12;
        icon12.addFile(QString::fromUtf8(":/QUI/icon/xMinus.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionViewXMinus->setIcon(icon12);
        actionViewYPlus = new QAction(MainWindow);
        actionViewYPlus->setObjectName(QString::fromUtf8("actionViewYPlus"));
        actionViewYPlus->setEnabled(false);
        QIcon icon13;
        icon13.addFile(QString::fromUtf8(":/QUI/icon/yPlus.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionViewYPlus->setIcon(icon13);
        actionViewYMinus = new QAction(MainWindow);
        actionViewYMinus->setObjectName(QString::fromUtf8("actionViewYMinus"));
        actionViewYMinus->setEnabled(false);
        QIcon icon14;
        icon14.addFile(QString::fromUtf8(":/QUI/icon/yMinus.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionViewYMinus->setIcon(icon14);
        actionViewZPlus = new QAction(MainWindow);
        actionViewZPlus->setObjectName(QString::fromUtf8("actionViewZPlus"));
        actionViewZPlus->setEnabled(false);
        QIcon icon15;
        icon15.addFile(QString::fromUtf8(":/QUI/icon/zPlus.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionViewZPlus->setIcon(icon15);
        actionViewZMinus = new QAction(MainWindow);
        actionViewZMinus->setObjectName(QString::fromUtf8("actionViewZMinus"));
        actionViewZMinus->setEnabled(false);
        QIcon icon16;
        icon16.addFile(QString::fromUtf8(":/QUI/icon/zMinus.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionViewZMinus->setIcon(icon16);
        actionFitView = new QAction(MainWindow);
        actionFitView->setObjectName(QString::fromUtf8("actionFitView"));
        actionFitView->setEnabled(false);
        QIcon icon17;
        icon17.addFile(QString::fromUtf8(":/QUI/icon/fit.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionFitView->setIcon(icon17);
        actionSelectOff = new QAction(MainWindow);
        actionSelectOff->setObjectName(QString::fromUtf8("actionSelectOff"));
        actionSelectOff->setCheckable(true);
        actionSelectOff->setChecked(true);
        actionSelectOff->setEnabled(false);
        QIcon icon18;
        icon18.addFile(QString::fromUtf8(":/QUI/icon/selectOff.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionSelectOff->setIcon(icon18);
        actionSelectMeshNode = new QAction(MainWindow);
        actionSelectMeshNode->setObjectName(QString::fromUtf8("actionSelectMeshNode"));
        actionSelectMeshNode->setCheckable(true);
        actionSelectMeshNode->setEnabled(false);
        QIcon icon19;
        icon19.addFile(QString::fromUtf8(":/QUI/icon/selectNode.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionSelectMeshNode->setIcon(icon19);
        actionSelectMeshCell = new QAction(MainWindow);
        actionSelectMeshCell->setObjectName(QString::fromUtf8("actionSelectMeshCell"));
        actionSelectMeshCell->setCheckable(true);
        actionSelectMeshCell->setEnabled(false);
        QIcon icon20;
        icon20.addFile(QString::fromUtf8(":/QUI/icon/selectElement.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionSelectMeshCell->setIcon(icon20);
        actionSolve_Options = new QAction(MainWindow);
        actionSolve_Options->setObjectName(QString::fromUtf8("actionSolve_Options"));
        actionSolve_Options->setIcon(icon9);
        actionGraph_Options = new QAction(MainWindow);
        actionGraph_Options->setObjectName(QString::fromUtf8("actionGraph_Options"));
        QIcon icon21;
        icon21.addFile(QString::fromUtf8(":/QUI/icon/graphOption.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionGraph_Options->setIcon(icon21);
        actionSurfaceMesh = new QAction(MainWindow);
        actionSurfaceMesh->setObjectName(QString::fromUtf8("actionSurfaceMesh"));
        actionSurfaceMesh->setEnabled(false);
        QIcon icon22;
        icon22.addFile(QString::fromUtf8(":/QUI/icon/surfaceMesh.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionSurfaceMesh->setIcon(icon22);
        actionSolidMesh = new QAction(MainWindow);
        actionSolidMesh->setObjectName(QString::fromUtf8("actionSolidMesh"));
        actionSolidMesh->setEnabled(false);
        QIcon icon23;
        icon23.addFile(QString::fromUtf8(":/QUI/icon/solidMesh.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionSolidMesh->setIcon(icon23);
        actionExportMesh = new QAction(MainWindow);
        actionExportMesh->setObjectName(QString::fromUtf8("actionExportMesh"));
        actionExportMesh->setEnabled(false);
        QIcon icon24;
        icon24.addFile(QString::fromUtf8(":/QUI/icon/exportMesh.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionExportMesh->setIcon(icon24);
        actionUser_Manual = new QAction(MainWindow);
        actionUser_Manual->setObjectName(QString::fromUtf8("actionUser_Manual"));
        actionUser_Manual->setCheckable(true);
        actionUser_Manual->setChecked(true);
        QIcon icon25;
        icon25.addFile(QString::fromUtf8(":/QUI/icon/help.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionUser_Manual->setIcon(icon25);
        actionAbout = new QAction(MainWindow);
        actionAbout->setObjectName(QString::fromUtf8("actionAbout"));
        QIcon icon26;
        icon26.addFile(QString::fromUtf8(":/QUI/icon/about_us.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionAbout->setIcon(icon26);
        actionDisplayNode = new QAction(MainWindow);
        actionDisplayNode->setObjectName(QString::fromUtf8("actionDisplayNode"));
        actionDisplayNode->setCheckable(true);
        actionDisplayNode->setEnabled(false);
        QIcon icon27;
        icon27.addFile(QString::fromUtf8(":/QUI/icon/node.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionDisplayNode->setIcon(icon27);
        actionDisplayWireFrame = new QAction(MainWindow);
        actionDisplayWireFrame->setObjectName(QString::fromUtf8("actionDisplayWireFrame"));
        actionDisplayWireFrame->setCheckable(true);
        actionDisplayWireFrame->setChecked(false);
        actionDisplayWireFrame->setEnabled(false);
        QIcon icon28;
        icon28.addFile(QString::fromUtf8(":/QUI/icon/wireFrame.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionDisplayWireFrame->setIcon(icon28);
        actionDisplaySurface = new QAction(MainWindow);
        actionDisplaySurface->setObjectName(QString::fromUtf8("actionDisplaySurface"));
        actionDisplaySurface->setCheckable(true);
        actionDisplaySurface->setEnabled(false);
        QIcon icon29;
        icon29.addFile(QString::fromUtf8(":/QUI/icon/face.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionDisplaySurface->setIcon(icon29);
        actionDisplaySurfaceEdge = new QAction(MainWindow);
        actionDisplaySurfaceEdge->setObjectName(QString::fromUtf8("actionDisplaySurfaceEdge"));
        actionDisplaySurfaceEdge->setCheckable(true);
        actionDisplaySurfaceEdge->setChecked(true);
        actionDisplaySurfaceEdge->setEnabled(false);
        QIcon icon30;
        icon30.addFile(QString::fromUtf8(":/QUI/icon/faceWithEdge.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionDisplaySurfaceEdge->setIcon(icon30);
        actionCreate_Set = new QAction(MainWindow);
        actionCreate_Set->setObjectName(QString::fromUtf8("actionCreate_Set"));
        actionCreate_Set->setEnabled(false);
        QIcon icon31;
        icon31.addFile(QString::fromUtf8(":/QUI/icon/meshComponent.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionCreate_Set->setIcon(icon31);
        action2DPlot = new QAction(MainWindow);
        action2DPlot->setObjectName(QString::fromUtf8("action2DPlot"));
        action3DGraph = new QAction(MainWindow);
        action3DGraph->setObjectName(QString::fromUtf8("action3DGraph"));
        actionSave_Script = new QAction(MainWindow);
        actionSave_Script->setObjectName(QString::fromUtf8("actionSave_Script"));
        QIcon icon32;
        icon32.addFile(QString::fromUtf8(":/QUI/icon/saveScript.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionSave_Script->setIcon(icon32);
        actionExecute_Script = new QAction(MainWindow);
        actionExecute_Script->setObjectName(QString::fromUtf8("actionExecute_Script"));
        QIcon icon33;
        icon33.addFile(QString::fromUtf8(":/QUI/icon/execScript.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionExecute_Script->setIcon(icon33);
        actionGenMesh = new QAction(MainWindow);
        actionGenMesh->setObjectName(QString::fromUtf8("actionGenMesh"));
        actionGenMesh->setEnabled(false);
        QIcon icon34;
        icon34.addFile(QString::fromUtf8(":/QUI/icon/solumationsetting.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionGenMesh->setIcon(icon34);
        actionSave_Picture = new QAction(MainWindow);
        actionSave_Picture->setObjectName(QString::fromUtf8("actionSave_Picture"));
        QIcon icon35;
        icon35.addFile(QString::fromUtf8(":/QUI/icon/saveImage.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionSave_Picture->setIcon(icon35);
        actionBoxMeshNode = new QAction(MainWindow);
        actionBoxMeshNode->setObjectName(QString::fromUtf8("actionBoxMeshNode"));
        actionBoxMeshNode->setCheckable(true);
        actionBoxMeshNode->setEnabled(false);
        QIcon icon36;
        icon36.addFile(QString::fromUtf8(":/QUI/icon/boxNode.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionBoxMeshNode->setIcon(icon36);
        actionBoxMeshCell = new QAction(MainWindow);
        actionBoxMeshCell->setObjectName(QString::fromUtf8("actionBoxMeshCell"));
        actionBoxMeshCell->setCheckable(true);
        actionBoxMeshCell->setEnabled(false);
        QIcon icon37;
        icon37.addFile(QString::fromUtf8(":/QUI/icon/boxCell.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionBoxMeshCell->setIcon(icon37);
        actionStart_Page = new QAction(MainWindow);
        actionStart_Page->setObjectName(QString::fromUtf8("actionStart_Page"));
        actionPre_Window = new QAction(MainWindow);
        actionPre_Window->setObjectName(QString::fromUtf8("actionPre_Window"));
        actionChecking = new QAction(MainWindow);
        actionChecking->setObjectName(QString::fromUtf8("actionChecking"));
        actionChecking->setEnabled(false);
        QIcon icon38;
        icon38.addFile(QString::fromUtf8(":/QUI/icon/meshChecking.png"), QSize(), QIcon::Active, QIcon::On);
        actionChecking->setIcon(icon38);
        actionCreateBox = new QAction(MainWindow);
        actionCreateBox->setObjectName(QString::fromUtf8("actionCreateBox"));
        QIcon icon39;
        icon39.addFile(QString::fromUtf8(":/QUI/geometry/box.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionCreateBox->setIcon(icon39);
        actionCreateCylinder = new QAction(MainWindow);
        actionCreateCylinder->setObjectName(QString::fromUtf8("actionCreateCylinder"));
        QIcon icon40;
        icon40.addFile(QString::fromUtf8(":/QUI/geometry/cylinder.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionCreateCylinder->setIcon(icon40);
        actionCreaterSphere = new QAction(MainWindow);
        actionCreaterSphere->setObjectName(QString::fromUtf8("actionCreaterSphere"));
        QIcon icon41;
        icon41.addFile(QString::fromUtf8(":/QUI/geometry/sphere.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionCreaterSphere->setIcon(icon41);
        actionChamfer = new QAction(MainWindow);
        actionChamfer->setObjectName(QString::fromUtf8("actionChamfer"));
        QIcon icon42;
        icon42.addFile(QString::fromUtf8(":/QUI/geometry/chamfer.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionChamfer->setIcon(icon42);
        actionFillet = new QAction(MainWindow);
        actionFillet->setObjectName(QString::fromUtf8("actionFillet"));
        QIcon icon43;
        icon43.addFile(QString::fromUtf8(":/QUI/geometry/fillet.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionFillet->setIcon(icon43);
        actionBoolCut = new QAction(MainWindow);
        actionBoolCut->setObjectName(QString::fromUtf8("actionBoolCut"));
        QIcon icon44;
        icon44.addFile(QString::fromUtf8(":/QUI/geometry/cut.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionBoolCut->setIcon(icon44);
        actionBoolFause = new QAction(MainWindow);
        actionBoolFause->setObjectName(QString::fromUtf8("actionBoolFause"));
        QIcon icon45;
        icon45.addFile(QString::fromUtf8(":/QUI/geometry/fuse.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionBoolFause->setIcon(icon45);
        actionBoolCommon = new QAction(MainWindow);
        actionBoolCommon->setObjectName(QString::fromUtf8("actionBoolCommon"));
        QIcon icon46;
        icon46.addFile(QString::fromUtf8(":/QUI/geometry/common.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionBoolCommon->setIcon(icon46);
        actionUndo = new QAction(MainWindow);
        actionUndo->setObjectName(QString::fromUtf8("actionUndo"));
        QIcon icon47;
        icon47.addFile(QString::fromUtf8(":/QUI/geometry/undo.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionUndo->setIcon(icon47);
        actionRedo = new QAction(MainWindow);
        actionRedo->setObjectName(QString::fromUtf8("actionRedo"));
        QIcon icon48;
        icon48.addFile(QString::fromUtf8(":/QUI/geometry/redo.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionRedo->setIcon(icon48);
        actionExportGeometry = new QAction(MainWindow);
        actionExportGeometry->setObjectName(QString::fromUtf8("actionExportGeometry"));
        QIcon icon49;
        icon49.addFile(QString::fromUtf8(":/QUI/icon/exportGeometry.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionExportGeometry->setIcon(icon49);
        actionCreaterCone = new QAction(MainWindow);
        actionCreaterCone->setObjectName(QString::fromUtf8("actionCreaterCone"));
        QIcon icon50;
        icon50.addFile(QString::fromUtf8(":/QUI/geometry/cone.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionCreaterCone->setIcon(icon50);
        actionMirrorFeature = new QAction(MainWindow);
        actionMirrorFeature->setObjectName(QString::fromUtf8("actionMirrorFeature"));
        QIcon icon51;
        icon51.addFile(QString::fromUtf8(":/QUI/geometry/mirror.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionMirrorFeature->setIcon(icon51);
        actionVariable_Fillet = new QAction(MainWindow);
        actionVariable_Fillet->setObjectName(QString::fromUtf8("actionVariable_Fillet"));
        QIcon icon52;
        icon52.addFile(QString::fromUtf8(":/QUI/geometry/variableFillet.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionVariable_Fillet->setIcon(icon52);
        actionExtrude = new QAction(MainWindow);
        actionExtrude->setObjectName(QString::fromUtf8("actionExtrude"));
        QIcon icon53;
        icon53.addFile(QString::fromUtf8(":/QUI/geometry/extrude.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionExtrude->setIcon(icon53);
        actionCreate_Point = new QAction(MainWindow);
        actionCreate_Point->setObjectName(QString::fromUtf8("actionCreate_Point"));
        QIcon icon54;
        icon54.addFile(QString::fromUtf8(":/QUI/geometry/point.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionCreate_Point->setIcon(icon54);
        actionCreate_Line = new QAction(MainWindow);
        actionCreate_Line->setObjectName(QString::fromUtf8("actionCreate_Line"));
        QIcon icon55;
        icon55.addFile(QString::fromUtf8(":/QUI/geometry/line.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionCreate_Line->setIcon(icon55);
        actionCreate_Face = new QAction(MainWindow);
        actionCreate_Face->setObjectName(QString::fromUtf8("actionCreate_Face"));
        QIcon icon56;
        icon56.addFile(QString::fromUtf8(":/QUI/geometry/face.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionCreate_Face->setIcon(icon56);
        actionMoveFeature = new QAction(MainWindow);
        actionMoveFeature->setObjectName(QString::fromUtf8("actionMoveFeature"));
        QIcon icon57;
        icon57.addFile(QString::fromUtf8(":/QUI/geometry/move.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionMoveFeature->setIcon(icon57);
        actionRotateFeature = new QAction(MainWindow);
        actionRotateFeature->setObjectName(QString::fromUtf8("actionRotateFeature"));
        QIcon icon58;
        icon58.addFile(QString::fromUtf8(":/QUI/geometry/Rotate.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionRotateFeature->setIcon(icon58);
        actionRevol = new QAction(MainWindow);
        actionRevol->setObjectName(QString::fromUtf8("actionRevol"));
        QIcon icon59;
        icon59.addFile(QString::fromUtf8(":/QUI/geometry/revolve.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionRevol->setIcon(icon59);
        actionLoft = new QAction(MainWindow);
        actionLoft->setObjectName(QString::fromUtf8("actionLoft"));
        QIcon icon60;
        icon60.addFile(QString::fromUtf8(":/QUI/geometry/loft.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionLoft->setIcon(icon60);
        actionCreateDatumPlane = new QAction(MainWindow);
        actionCreateDatumPlane->setObjectName(QString::fromUtf8("actionCreateDatumPlane"));
        QIcon icon61;
        icon61.addFile(QString::fromUtf8(":/QUI/icon/datumPlane.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionCreateDatumPlane->setIcon(icon61);
        actionDrawLine = new QAction(MainWindow);
        actionDrawLine->setObjectName(QString::fromUtf8("actionDrawLine"));
        actionDrawLine->setCheckable(false);
        QIcon icon62;
        icon62.addFile(QString::fromUtf8(":/QUI/icon/sketchLine.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionDrawLine->setIcon(icon62);
        actionDrawRectangle = new QAction(MainWindow);
        actionDrawRectangle->setObjectName(QString::fromUtf8("actionDrawRectangle"));
        actionDrawRectangle->setCheckable(false);
        QIcon icon63;
        icon63.addFile(QString::fromUtf8(":/QUI/icon/sketchRectangle.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionDrawRectangle->setIcon(icon63);
        actionDrawCircle = new QAction(MainWindow);
        actionDrawCircle->setObjectName(QString::fromUtf8("actionDrawCircle"));
        actionDrawCircle->setCheckable(false);
        QIcon icon64;
        icon64.addFile(QString::fromUtf8(":/QUI/icon/sketchCircle.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionDrawCircle->setIcon(icon64);
        actionCreate_Sketch = new QAction(MainWindow);
        actionCreate_Sketch->setObjectName(QString::fromUtf8("actionCreate_Sketch"));
        actionCreate_Sketch->setCheckable(true);
        QIcon icon65;
        icon65.addFile(QString::fromUtf8(":/QUI/icon/createSketch.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionCreate_Sketch->setIcon(icon65);
        actionDrawArc = new QAction(MainWindow);
        actionDrawArc->setObjectName(QString::fromUtf8("actionDrawArc"));
        actionDrawArc->setCheckable(false);
        actionDrawArc->setEnabled(true);
        QIcon icon66;
        icon66.addFile(QString::fromUtf8(":/QUI/icon/sketchArc.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionDrawArc->setIcon(icon66);
        actionDrawPolyline = new QAction(MainWindow);
        actionDrawPolyline->setObjectName(QString::fromUtf8("actionDrawPolyline"));
        QIcon icon67;
        icon67.addFile(QString::fromUtf8(":/QUI/icon/sketchPolyLine.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionDrawPolyline->setIcon(icon67);
        actionMakeMatrix = new QAction(MainWindow);
        actionMakeMatrix->setObjectName(QString::fromUtf8("actionMakeMatrix"));
        QIcon icon68;
        icon68.addFile(QString::fromUtf8(":/QUI/geometry/matrix.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionMakeMatrix->setIcon(icon68);
        actionSweep = new QAction(MainWindow);
        actionSweep->setObjectName(QString::fromUtf8("actionSweep"));
        QIcon icon69;
        icon69.addFile(QString::fromUtf8(":/QUI/geometry/sweep.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionSweep->setIcon(icon69);
        actionDrawSpline = new QAction(MainWindow);
        actionDrawSpline->setObjectName(QString::fromUtf8("actionDrawSpline"));
        QIcon icon70;
        icon70.addFile(QString::fromUtf8(":/QUI/icon/sketchSpline.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionDrawSpline->setIcon(icon70);
        actionDisplayPoint = new QAction(MainWindow);
        actionDisplayPoint->setObjectName(QString::fromUtf8("actionDisplayPoint"));
        actionDisplayPoint->setCheckable(true);
        actionDisplayPoint->setChecked(false);
        QIcon icon71;
        icon71.addFile(QString::fromUtf8(":/QUI/geometry/pointDisplay.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionDisplayPoint->setIcon(icon71);
        actionDisplayCurve = new QAction(MainWindow);
        actionDisplayCurve->setObjectName(QString::fromUtf8("actionDisplayCurve"));
        actionDisplayCurve->setCheckable(true);
        actionDisplayCurve->setChecked(false);
        QIcon icon72;
        icon72.addFile(QString::fromUtf8(":/QUI/geometry/edgeDisplay.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionDisplayCurve->setIcon(icon72);
        actionDisplayFace = new QAction(MainWindow);
        actionDisplayFace->setObjectName(QString::fromUtf8("actionDisplayFace"));
        actionDisplayFace->setCheckable(true);
        actionDisplayFace->setChecked(true);
        QIcon icon73;
        icon73.addFile(QString::fromUtf8(":/QUI/geometry/facedisplay.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionDisplayFace->setIcon(icon73);
        actionSelectPoint = new QAction(MainWindow);
        actionSelectPoint->setObjectName(QString::fromUtf8("actionSelectPoint"));
        actionSelectPoint->setCheckable(true);
        QIcon icon74;
        icon74.addFile(QString::fromUtf8(":/QUI/geometry/selectpoint.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionSelectPoint->setIcon(icon74);
        actionSelectCurve = new QAction(MainWindow);
        actionSelectCurve->setObjectName(QString::fromUtf8("actionSelectCurve"));
        actionSelectCurve->setCheckable(true);
        QIcon icon75;
        icon75.addFile(QString::fromUtf8(":/QUI/geometry/selectwire.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionSelectCurve->setIcon(icon75);
        actionSelectFace = new QAction(MainWindow);
        actionSelectFace->setObjectName(QString::fromUtf8("actionSelectFace"));
        actionSelectFace->setCheckable(true);
        QIcon icon76;
        icon76.addFile(QString::fromUtf8(":/QUI/geometry/selectface.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionSelectFace->setIcon(icon76);
        actionSelectGeometryBody = new QAction(MainWindow);
        actionSelectGeometryBody->setObjectName(QString::fromUtf8("actionSelectGeometryBody"));
        actionSelectGeometryBody->setCheckable(true);
        QIcon icon77;
        icon77.addFile(QString::fromUtf8(":/QUI/geometry/selectbody.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionSelectGeometryBody->setIcon(icon77);
        actionPluginManager = new QAction(MainWindow);
        actionPluginManager->setObjectName(QString::fromUtf8("actionPluginManager"));
        actionUser_Guidance = new QAction(MainWindow);
        actionUser_Guidance->setObjectName(QString::fromUtf8("actionUser_Guidance"));
        actionUser_Guidance->setCheckable(true);
        actionUser_Guidance->setChecked(true);
        actionMeasure_Distance = new QAction(MainWindow);
        actionMeasure_Distance->setObjectName(QString::fromUtf8("actionMeasure_Distance"));
        QIcon icon78;
        icon78.addFile(QString::fromUtf8(":/QUI/geometry/geoMeasure.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionMeasure_Distance->setIcon(icon78);
        actionMeasure = new QAction(MainWindow);
        actionMeasure->setObjectName(QString::fromUtf8("actionMeasure"));
        actionGeoSplitter = new QAction(MainWindow);
        actionGeoSplitter->setObjectName(QString::fromUtf8("actionGeoSplitter"));
        QIcon icon79;
        icon79.addFile(QString::fromUtf8(":/QUI/geometry/geoSSplit.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionGeoSplitter->setIcon(icon79);
        actionCreateGeoComponent = new QAction(MainWindow);
        actionCreateGeoComponent->setObjectName(QString::fromUtf8("actionCreateGeoComponent"));
        actionCreateGeoComponent->setEnabled(false);
        QIcon icon80;
        icon80.addFile(QString::fromUtf8(":/QUI/icon/geoComponent.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionCreateGeoComponent->setIcon(icon80);
        actionFluidMesh = new QAction(MainWindow);
        actionFluidMesh->setObjectName(QString::fromUtf8("actionFluidMesh"));
        actionFluidMesh->setEnabled(false);
        actionFluidMesh->setIcon(icon23);
        actionFilterMesh = new QAction(MainWindow);
        actionFilterMesh->setObjectName(QString::fromUtf8("actionFilterMesh"));
        actionFilterMesh->setEnabled(false);
        QIcon icon81;
        icon81.addFile(QString::fromUtf8(":/QUI/icon/meshFilter.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionFilterMesh->setIcon(icon81);
        actionFillHole = new QAction(MainWindow);
        actionFillHole->setObjectName(QString::fromUtf8("actionFillHole"));
        QIcon icon82;
        icon82.addFile(QString::fromUtf8(":/QUI/geometry/geoFillHole.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionFillHole->setIcon(icon82);
        actionRemoveSurface = new QAction(MainWindow);
        actionRemoveSurface->setObjectName(QString::fromUtf8("actionRemoveSurface"));
        QIcon icon83;
        icon83.addFile(QString::fromUtf8(":/QUI/geometry/geoRemoveFace.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionRemoveSurface->setIcon(icon83);
        actionFillGap = new QAction(MainWindow);
        actionFillGap->setObjectName(QString::fromUtf8("actionFillGap"));
        QIcon icon84;
        icon84.addFile(QString::fromUtf8(":/QUI/geometry/geoFixSurface.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionFillGap->setIcon(icon84);
        actionVTKTranslation = new QAction(MainWindow);
        actionVTKTranslation->setObjectName(QString::fromUtf8("actionVTKTranslation"));
        actionVTKTranslation->setCheckable(false);
        actionVTKTranslation->setEnabled(false);
        QIcon icon85;
        icon85.addFile(QString::fromUtf8(":/QUI/icon/meshmodeling.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionVTKTranslation->setIcon(icon85);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        gridLayout = new QGridLayout(centralwidget);
        gridLayout->setObjectName(QString::fromUtf8("gridLayout"));
        mdiArea = new QMdiArea(centralwidget);
        mdiArea->setObjectName(QString::fromUtf8("mdiArea"));

        gridLayout->addWidget(mdiArea, 0, 0, 1, 1);

        MainWindow->setCentralWidget(centralwidget);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        MainWindow->setStatusBar(statusbar);
        FileToolBar = new QToolBar(MainWindow);
        FileToolBar->setObjectName(QString::fromUtf8("FileToolBar"));
        FileToolBar->setToolButtonStyle(Qt::ToolButtonFollowStyle);
        MainWindow->addToolBar(Qt::TopToolBarArea, FileToolBar);
        SolveToolBar = new QToolBar(MainWindow);
        SolveToolBar->setObjectName(QString::fromUtf8("SolveToolBar"));
        SolveToolBar->setToolButtonStyle(Qt::ToolButtonFollowStyle);
        MainWindow->addToolBar(Qt::TopToolBarArea, SolveToolBar);
        ViewToolBar = new QToolBar(MainWindow);
        ViewToolBar->setObjectName(QString::fromUtf8("ViewToolBar"));
        ViewToolBar->setToolButtonStyle(Qt::ToolButtonFollowStyle);
        MainWindow->addToolBar(Qt::TopToolBarArea, ViewToolBar);
        SelectToolBar = new QToolBar(MainWindow);
        SelectToolBar->setObjectName(QString::fromUtf8("SelectToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, SelectToolBar);
        MeshToolBar = new QToolBar(MainWindow);
        MeshToolBar->setObjectName(QString::fromUtf8("MeshToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, MeshToolBar);
        DisplayToolBar = new QToolBar(MainWindow);
        DisplayToolBar->setObjectName(QString::fromUtf8("DisplayToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, DisplayToolBar);
        SetToolBar = new QToolBar(MainWindow);
        SetToolBar->setObjectName(QString::fromUtf8("SetToolBar"));
        SetToolBar->setEnabled(true);
        MainWindow->addToolBar(Qt::TopToolBarArea, SetToolBar);
        RedoToolBar = new QToolBar(MainWindow);
        RedoToolBar->setObjectName(QString::fromUtf8("RedoToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, RedoToolBar);
        StartSketchToolBar = new QToolBar(MainWindow);
        StartSketchToolBar->setObjectName(QString::fromUtf8("StartSketchToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, StartSketchToolBar);
        MainWindow->insertToolBarBreak(StartSketchToolBar);
        GeomertryFeatureToolBar = new QToolBar(MainWindow);
        GeomertryFeatureToolBar->setObjectName(QString::fromUtf8("GeomertryFeatureToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, GeomertryFeatureToolBar);
        ChamferToolBar = new QToolBar(MainWindow);
        ChamferToolBar->setObjectName(QString::fromUtf8("ChamferToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, ChamferToolBar);
        BoolToolBar = new QToolBar(MainWindow);
        BoolToolBar->setObjectName(QString::fromUtf8("BoolToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, BoolToolBar);
        FeatureOpertionToolBar = new QToolBar(MainWindow);
        FeatureOpertionToolBar->setObjectName(QString::fromUtf8("FeatureOpertionToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, FeatureOpertionToolBar);
        SketchToolBar = new QToolBar(MainWindow);
        SketchToolBar->setObjectName(QString::fromUtf8("SketchToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, SketchToolBar);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 1678, 23));
        menuFile = new QMenu(menubar);
        menuFile->setObjectName(QString::fromUtf8("menuFile"));
        menuView = new QMenu(menubar);
        menuView->setObjectName(QString::fromUtf8("menuView"));
        menuHelp = new QMenu(menubar);
        menuHelp->setObjectName(QString::fromUtf8("menuHelp"));
        menuSolve = new QMenu(menubar);
        menuSolve->setObjectName(QString::fromUtf8("menuSolve"));
        menuSolve->setEnabled(true);
        menuSettings = new QMenu(menubar);
        menuSettings->setObjectName(QString::fromUtf8("menuSettings"));
        menuLanguage = new QMenu(menuSettings);
        menuLanguage->setObjectName(QString::fromUtf8("menuLanguage"));
        menuMesher = new QMenu(menubar);
        menuMesher->setObjectName(QString::fromUtf8("menuMesher"));
        menuView_2 = new QMenu(menuMesher);
        menuView_2->setObjectName(QString::fromUtf8("menuView_2"));
        menuSelect = new QMenu(menuMesher);
        menuSelect->setObjectName(QString::fromUtf8("menuSelect"));
        menuPost = new QMenu(menubar);
        menuPost->setObjectName(QString::fromUtf8("menuPost"));
        menuWindows = new QMenu(menubar);
        menuWindows->setObjectName(QString::fromUtf8("menuWindows"));
        menuGeometry = new QMenu(menubar);
        menuGeometry->setObjectName(QString::fromUtf8("menuGeometry"));
        menuFeature_Modeling = new QMenu(menuGeometry);
        menuFeature_Modeling->setObjectName(QString::fromUtf8("menuFeature_Modeling"));
        menuView_3 = new QMenu(menuGeometry);
        menuView_3->setObjectName(QString::fromUtf8("menuView_3"));
        menuFeature_Operation = new QMenu(menuGeometry);
        menuFeature_Operation->setObjectName(QString::fromUtf8("menuFeature_Operation"));
        menuSelect_2 = new QMenu(menuGeometry);
        menuSelect_2->setObjectName(QString::fromUtf8("menuSelect_2"));
        menuSketch = new QMenu(menuGeometry);
        menuSketch->setObjectName(QString::fromUtf8("menuSketch"));
        menuPlugins = new QMenu(menubar);
        menuPlugins->setObjectName(QString::fromUtf8("menuPlugins"));
        MainWindow->setMenuBar(menubar);
        MeasureToolBar = new QToolBar(MainWindow);
        MeasureToolBar->setObjectName(QString::fromUtf8("MeasureToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, MeasureToolBar);

        FileToolBar->addAction(actionNew);
        FileToolBar->addAction(actionOpen);
        FileToolBar->addAction(actionSave);
        FileToolBar->addAction(actionImportMesh);
        FileToolBar->addAction(actionImportGeometry);
        SolveToolBar->addAction(actionSolve);
        ViewToolBar->addAction(actionFitView);
        ViewToolBar->addAction(actionViewXPlus);
        ViewToolBar->addAction(actionViewXMinus);
        ViewToolBar->addAction(actionViewYPlus);
        ViewToolBar->addAction(actionViewYMinus);
        ViewToolBar->addAction(actionViewZPlus);
        ViewToolBar->addAction(actionViewZMinus);
        ViewToolBar->addSeparator();
        SelectToolBar->addAction(actionSelectOff);
        SelectToolBar->addAction(actionSelectMeshNode);
        SelectToolBar->addAction(actionSelectMeshCell);
        SelectToolBar->addAction(actionBoxMeshNode);
        SelectToolBar->addAction(actionBoxMeshCell);
        SelectToolBar->addSeparator();
        SelectToolBar->addAction(actionSelectPoint);
        SelectToolBar->addAction(actionSelectCurve);
        SelectToolBar->addAction(actionSelectFace);
        SelectToolBar->addAction(actionSelectGeometryBody);
        MeshToolBar->addAction(actionSurfaceMesh);
        MeshToolBar->addAction(actionSolidMesh);
        MeshToolBar->addAction(actionFluidMesh);
        MeshToolBar->addAction(actionGenMesh);
        DisplayToolBar->addAction(actionDisplayNode);
        DisplayToolBar->addAction(actionDisplayWireFrame);
        DisplayToolBar->addAction(actionDisplaySurface);
        DisplayToolBar->addAction(actionDisplaySurfaceEdge);
        DisplayToolBar->addSeparator();
        DisplayToolBar->addAction(actionDisplayPoint);
        DisplayToolBar->addAction(actionDisplayCurve);
        DisplayToolBar->addAction(actionDisplayFace);
        SetToolBar->addAction(actionChecking);
        SetToolBar->addAction(actionFilterMesh);
        SetToolBar->addAction(actionCreate_Set);
        SetToolBar->addAction(actionCreateGeoComponent);
        SetToolBar->addAction(actionVTKTranslation);
        RedoToolBar->addAction(actionUndo);
        RedoToolBar->addAction(actionRedo);
        StartSketchToolBar->addAction(actionCreate_Sketch);
        GeomertryFeatureToolBar->addAction(actionCreateBox);
        GeomertryFeatureToolBar->addAction(actionCreateCylinder);
        GeomertryFeatureToolBar->addAction(actionCreaterCone);
        GeomertryFeatureToolBar->addAction(actionCreaterSphere);
        GeomertryFeatureToolBar->addAction(actionCreate_Face);
        GeomertryFeatureToolBar->addAction(actionCreate_Line);
        GeomertryFeatureToolBar->addAction(actionCreate_Point);
        GeomertryFeatureToolBar->addAction(actionCreateDatumPlane);
        ChamferToolBar->addAction(actionChamfer);
        ChamferToolBar->addAction(actionFillet);
        ChamferToolBar->addAction(actionVariable_Fillet);
        BoolToolBar->addAction(actionBoolCut);
        BoolToolBar->addAction(actionBoolFause);
        BoolToolBar->addAction(actionBoolCommon);
        FeatureOpertionToolBar->addAction(actionMirrorFeature);
        FeatureOpertionToolBar->addAction(actionMoveFeature);
        FeatureOpertionToolBar->addAction(actionRotateFeature);
        FeatureOpertionToolBar->addAction(actionMakeMatrix);
        FeatureOpertionToolBar->addAction(actionExtrude);
        FeatureOpertionToolBar->addAction(actionRevol);
        FeatureOpertionToolBar->addAction(actionLoft);
        FeatureOpertionToolBar->addAction(actionSweep);
        FeatureOpertionToolBar->addAction(actionGeoSplitter);
        FeatureOpertionToolBar->addAction(actionFillHole);
        FeatureOpertionToolBar->addAction(actionRemoveSurface);
        FeatureOpertionToolBar->addAction(actionFillGap);
        SketchToolBar->addAction(actionDrawLine);
        SketchToolBar->addAction(actionDrawRectangle);
        SketchToolBar->addAction(actionDrawCircle);
        SketchToolBar->addAction(actionDrawArc);
        SketchToolBar->addAction(actionDrawPolyline);
        SketchToolBar->addAction(actionDrawSpline);
        menubar->addAction(menuFile->menuAction());
        menubar->addAction(menuView->menuAction());
        menubar->addAction(menuGeometry->menuAction());
        menubar->addAction(menuMesher->menuAction());
        menubar->addAction(menuSolve->menuAction());
        menubar->addAction(menuPost->menuAction());
        menubar->addAction(menuWindows->menuAction());
        menubar->addAction(menuSettings->menuAction());
        menubar->addAction(menuPlugins->menuAction());
        menubar->addAction(menuHelp->menuAction());
        menuFile->addAction(actionNew);
        menuFile->addAction(actionOpen);
        menuFile->addAction(actionClose);
        menuFile->addSeparator();
        menuFile->addAction(actionImportMesh);
        menuFile->addAction(actionExportMesh);
        menuFile->addAction(actionImportGeometry);
        menuFile->addAction(actionExportGeometry);
        menuFile->addSeparator();
        menuFile->addAction(actionSave);
        menuFile->addAction(actionSaveAs);
        menuFile->addSeparator();
        menuFile->addAction(actionSave_Script);
        menuFile->addAction(actionExecute_Script);
        menuFile->addSeparator();
        menuFile->addAction(actionSave_Picture);
        menuFile->addAction(actionWorkingDir);
        menuFile->addSeparator();
        menuView->addAction(actionFitView);
        menuView->addAction(actionViewXPlus);
        menuView->addAction(actionViewXMinus);
        menuView->addAction(actionViewYPlus);
        menuView->addAction(actionViewYMinus);
        menuView->addAction(actionViewZPlus);
        menuView->addAction(actionViewZMinus);
        menuView->addSeparator();
        menuHelp->addAction(actionUser_Guidance);
        menuHelp->addAction(actionUser_Manual);
        menuHelp->addAction(actionAbout);
        menuSolve->addAction(actionSolve);
        menuSolve->addSeparator();
        menuSolve->addAction(actionSolver_Manager);
        menuSettings->addAction(actionGraph_Options);
        menuSettings->addSeparator();
        menuSettings->addAction(menuLanguage->menuAction());
        menuLanguage->addAction(actionChinese);
        menuLanguage->addAction(actionEnglish);
        menuMesher->addAction(actionSurfaceMesh);
        menuMesher->addAction(actionSolidMesh);
        menuMesher->addAction(actionFluidMesh);
        menuMesher->addAction(actionGenMesh);
        menuMesher->addSeparator();
        menuMesher->addAction(actionChecking);
        menuMesher->addAction(actionFilterMesh);
        menuMesher->addAction(actionCreate_Set);
        menuMesher->addAction(menuView_2->menuAction());
        menuMesher->addAction(menuSelect->menuAction());
        menuView_2->addAction(actionDisplayNode);
        menuView_2->addAction(actionDisplayWireFrame);
        menuView_2->addAction(actionDisplaySurface);
        menuView_2->addAction(actionDisplaySurfaceEdge);
        menuSelect->addAction(actionSelectOff);
        menuSelect->addAction(actionSelectMeshNode);
        menuSelect->addAction(actionSelectMeshCell);
        menuSelect->addAction(actionBoxMeshNode);
        menuSelect->addAction(actionBoxMeshCell);
        menuPost->addAction(action2DPlot);
        menuPost->addAction(action3DGraph);
        menuWindows->addAction(actionStart_Page);
        menuWindows->addAction(actionPre_Window);
        menuGeometry->addAction(actionUndo);
        menuGeometry->addAction(actionRedo);
        menuGeometry->addSeparator();
        menuGeometry->addAction(menuFeature_Modeling->menuAction());
        menuGeometry->addAction(menuFeature_Operation->menuAction());
        menuGeometry->addAction(menuSketch->menuAction());
        menuGeometry->addSeparator();
        menuGeometry->addAction(menuView_3->menuAction());
        menuGeometry->addAction(menuSelect_2->menuAction());
        menuGeometry->addAction(actionMeasure);
        menuFeature_Modeling->addAction(actionCreateBox);
        menuFeature_Modeling->addAction(actionCreateCylinder);
        menuFeature_Modeling->addAction(actionCreaterCone);
        menuFeature_Modeling->addAction(actionCreaterSphere);
        menuFeature_Modeling->addAction(actionCreate_Point);
        menuFeature_Modeling->addAction(actionCreate_Line);
        menuFeature_Modeling->addAction(actionCreate_Face);
        menuFeature_Modeling->addSeparator();
        menuFeature_Modeling->addAction(actionCreateDatumPlane);
        menuView_3->addAction(actionDisplayPoint);
        menuView_3->addAction(actionDisplayCurve);
        menuView_3->addAction(actionDisplayFace);
        menuFeature_Operation->addAction(actionChamfer);
        menuFeature_Operation->addAction(actionFillet);
        menuFeature_Operation->addAction(actionVariable_Fillet);
        menuFeature_Operation->addSeparator();
        menuFeature_Operation->addAction(actionBoolCut);
        menuFeature_Operation->addAction(actionBoolFause);
        menuFeature_Operation->addAction(actionBoolCommon);
        menuFeature_Operation->addSeparator();
        menuFeature_Operation->addAction(actionMirrorFeature);
        menuFeature_Operation->addAction(actionMoveFeature);
        menuFeature_Operation->addAction(actionRotateFeature);
        menuFeature_Operation->addAction(actionMakeMatrix);
        menuFeature_Operation->addSeparator();
        menuFeature_Operation->addAction(actionExtrude);
        menuFeature_Operation->addAction(actionRevol);
        menuFeature_Operation->addAction(actionLoft);
        menuFeature_Operation->addAction(actionSweep);
        menuFeature_Operation->addAction(actionGeoSplitter);
        menuSelect_2->addAction(actionSelectOff);
        menuSelect_2->addSeparator();
        menuSelect_2->addAction(actionSelectPoint);
        menuSelect_2->addAction(actionSelectCurve);
        menuSelect_2->addAction(actionSelectFace);
        menuSelect_2->addAction(actionSelectGeometryBody);
        menuSketch->addAction(actionCreate_Sketch);
        menuSketch->addSeparator();
        menuSketch->addAction(actionDrawLine);
        menuSketch->addAction(actionDrawRectangle);
        menuSketch->addAction(actionDrawCircle);
        menuSketch->addAction(actionDrawArc);
        menuSketch->addAction(actionDrawPolyline);
        menuSketch->addAction(actionDrawSpline);
        menuPlugins->addAction(actionPluginManager);
        MeasureToolBar->addAction(actionMeasure_Distance);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "FastCAE", nullptr));
        actionNew->setText(QCoreApplication::translate("MainWindow", "New", nullptr));
#if QT_CONFIG(tooltip)
        actionNew->setToolTip(QCoreApplication::translate("MainWindow", "New", nullptr));
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        actionNew->setShortcut(QCoreApplication::translate("MainWindow", "Ctrl+N", nullptr));
#endif // QT_CONFIG(shortcut)
        actionOpen->setText(QCoreApplication::translate("MainWindow", "Open", nullptr));
#if QT_CONFIG(tooltip)
        actionOpen->setToolTip(QCoreApplication::translate("MainWindow", "Open", nullptr));
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        actionOpen->setShortcut(QCoreApplication::translate("MainWindow", "Ctrl+O", nullptr));
#endif // QT_CONFIG(shortcut)
        actionSave->setText(QCoreApplication::translate("MainWindow", "Save", nullptr));
#if QT_CONFIG(shortcut)
        actionSave->setShortcut(QCoreApplication::translate("MainWindow", "Ctrl+S", nullptr));
#endif // QT_CONFIG(shortcut)
        actionClose->setText(QCoreApplication::translate("MainWindow", "Close", nullptr));
#if QT_CONFIG(tooltip)
        actionClose->setToolTip(QCoreApplication::translate("MainWindow", "Close", nullptr));
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        actionClose->setShortcut(QCoreApplication::translate("MainWindow", "Ctrl+Q", nullptr));
#endif // QT_CONFIG(shortcut)
        actionSaveAs->setText(QCoreApplication::translate("MainWindow", "SaveAs", nullptr));
#if QT_CONFIG(shortcut)
        actionSaveAs->setShortcut(QCoreApplication::translate("MainWindow", "Ctrl+Shift+S", nullptr));
#endif // QT_CONFIG(shortcut)
        actionChinese->setText(QCoreApplication::translate("MainWindow", "Chinese", nullptr));
#if QT_CONFIG(tooltip)
        actionChinese->setToolTip(QCoreApplication::translate("MainWindow", "Chinese", nullptr));
#endif // QT_CONFIG(tooltip)
        actionEnglish->setText(QCoreApplication::translate("MainWindow", "English", nullptr));
#if QT_CONFIG(tooltip)
        actionEnglish->setToolTip(QCoreApplication::translate("MainWindow", "English", nullptr));
#endif // QT_CONFIG(tooltip)
        actionImportMesh->setText(QCoreApplication::translate("MainWindow", "Import Mesh", nullptr));
#if QT_CONFIG(shortcut)
        actionImportMesh->setShortcut(QCoreApplication::translate("MainWindow", "Ctrl+I", nullptr));
#endif // QT_CONFIG(shortcut)
        actionImportGeometry->setText(QCoreApplication::translate("MainWindow", "Import Geometry", nullptr));
#if QT_CONFIG(shortcut)
        actionImportGeometry->setShortcut(QCoreApplication::translate("MainWindow", "Ctrl+G", nullptr));
#endif // QT_CONFIG(shortcut)
        actionWorkingDir->setText(QCoreApplication::translate("MainWindow", "WorkingDir", nullptr));
        actionSolve->setText(QCoreApplication::translate("MainWindow", "Solve", nullptr));
#if QT_CONFIG(shortcut)
        actionSolve->setShortcut(QCoreApplication::translate("MainWindow", "F5", nullptr));
#endif // QT_CONFIG(shortcut)
        actionSolver_Manager->setText(QCoreApplication::translate("MainWindow", "Solver Manager", nullptr));
        actionViewXPlus->setText(QCoreApplication::translate("MainWindow", "ViewXPlus", nullptr));
        actionViewXMinus->setText(QCoreApplication::translate("MainWindow", "ViewXMinus", nullptr));
        actionViewYPlus->setText(QCoreApplication::translate("MainWindow", "ViewYPlus", nullptr));
        actionViewYMinus->setText(QCoreApplication::translate("MainWindow", "ViewYMinus", nullptr));
        actionViewZPlus->setText(QCoreApplication::translate("MainWindow", "ViewZPlus", nullptr));
        actionViewZMinus->setText(QCoreApplication::translate("MainWindow", "ViewZMinus", nullptr));
        actionFitView->setText(QCoreApplication::translate("MainWindow", "FitView", nullptr));
        actionSelectOff->setText(QCoreApplication::translate("MainWindow", "selectOff", nullptr));
        actionSelectMeshNode->setText(QCoreApplication::translate("MainWindow", "selectMeshNode", nullptr));
        actionSelectMeshCell->setText(QCoreApplication::translate("MainWindow", "selectMeshCell", nullptr));
        actionSolve_Options->setText(QCoreApplication::translate("MainWindow", "Solve Options", nullptr));
        actionGraph_Options->setText(QCoreApplication::translate("MainWindow", "Graph Options", nullptr));
        actionSurfaceMesh->setText(QCoreApplication::translate("MainWindow", "SurfaceMesh", nullptr));
        actionSolidMesh->setText(QCoreApplication::translate("MainWindow", "SolidMesh", nullptr));
        actionExportMesh->setText(QCoreApplication::translate("MainWindow", "Export Mesh", nullptr));
#if QT_CONFIG(shortcut)
        actionExportMesh->setShortcut(QCoreApplication::translate("MainWindow", "Ctrl+E", nullptr));
#endif // QT_CONFIG(shortcut)
        actionUser_Manual->setText(QCoreApplication::translate("MainWindow", "User Manual", nullptr));
        actionAbout->setText(QCoreApplication::translate("MainWindow", "About", nullptr));
        actionDisplayNode->setText(QCoreApplication::translate("MainWindow", "DisplayNode", nullptr));
        actionDisplayWireFrame->setText(QCoreApplication::translate("MainWindow", "DisplayWireFrame", nullptr));
        actionDisplaySurface->setText(QCoreApplication::translate("MainWindow", "DisplaySurface", nullptr));
        actionDisplaySurfaceEdge->setText(QCoreApplication::translate("MainWindow", "DisplaySurfaceEdge", nullptr));
#if QT_CONFIG(tooltip)
        actionDisplaySurfaceEdge->setToolTip(QCoreApplication::translate("MainWindow", "DisplaySurfaceEdge", nullptr));
#endif // QT_CONFIG(tooltip)
        actionCreate_Set->setText(QCoreApplication::translate("MainWindow", "Create Set", nullptr));
        action2DPlot->setText(QCoreApplication::translate("MainWindow", "2D Plot", nullptr));
        action3DGraph->setText(QCoreApplication::translate("MainWindow", "3D Graph", nullptr));
        actionSave_Script->setText(QCoreApplication::translate("MainWindow", "Save Script", nullptr));
        actionExecute_Script->setText(QCoreApplication::translate("MainWindow", "Execute Script", nullptr));
#if QT_CONFIG(shortcut)
        actionExecute_Script->setShortcut(QCoreApplication::translate("MainWindow", "Ctrl+R", nullptr));
#endif // QT_CONFIG(shortcut)
        actionGenMesh->setText(QCoreApplication::translate("MainWindow", "GenMesh", nullptr));
        actionSave_Picture->setText(QCoreApplication::translate("MainWindow", "Save Picture", nullptr));
        actionBoxMeshNode->setText(QCoreApplication::translate("MainWindow", "BoxMeshNode", nullptr));
        actionBoxMeshCell->setText(QCoreApplication::translate("MainWindow", "BoxMeshCell", nullptr));
        actionStart_Page->setText(QCoreApplication::translate("MainWindow", "Start Page", nullptr));
        actionPre_Window->setText(QCoreApplication::translate("MainWindow", "Pre Window", nullptr));
        actionChecking->setText(QCoreApplication::translate("MainWindow", "Checking", nullptr));
        actionCreateBox->setText(QCoreApplication::translate("MainWindow", "CreateBox", nullptr));
        actionCreateCylinder->setText(QCoreApplication::translate("MainWindow", "CreateCylinder", nullptr));
        actionCreaterSphere->setText(QCoreApplication::translate("MainWindow", "CreaterSphere", nullptr));
        actionChamfer->setText(QCoreApplication::translate("MainWindow", "Chamfer", nullptr));
        actionFillet->setText(QCoreApplication::translate("MainWindow", "Fillet", nullptr));
        actionBoolCut->setText(QCoreApplication::translate("MainWindow", "BoolCut", nullptr));
        actionBoolFause->setText(QCoreApplication::translate("MainWindow", "BoolFause", nullptr));
        actionBoolCommon->setText(QCoreApplication::translate("MainWindow", "BoolCommon", nullptr));
        actionUndo->setText(QCoreApplication::translate("MainWindow", "undo", nullptr));
#if QT_CONFIG(shortcut)
        actionUndo->setShortcut(QCoreApplication::translate("MainWindow", "Ctrl+Z", nullptr));
#endif // QT_CONFIG(shortcut)
        actionRedo->setText(QCoreApplication::translate("MainWindow", "redo", nullptr));
#if QT_CONFIG(shortcut)
        actionRedo->setShortcut(QCoreApplication::translate("MainWindow", "Ctrl+Y", nullptr));
#endif // QT_CONFIG(shortcut)
        actionExportGeometry->setText(QCoreApplication::translate("MainWindow", "ExportGeometry", nullptr));
        actionCreaterCone->setText(QCoreApplication::translate("MainWindow", "CreaterCone", nullptr));
        actionMirrorFeature->setText(QCoreApplication::translate("MainWindow", "MirrorFeature", nullptr));
        actionVariable_Fillet->setText(QCoreApplication::translate("MainWindow", "Variable Fillet", nullptr));
        actionExtrude->setText(QCoreApplication::translate("MainWindow", "Extrude", nullptr));
        actionCreate_Point->setText(QCoreApplication::translate("MainWindow", "Create Point", nullptr));
        actionCreate_Line->setText(QCoreApplication::translate("MainWindow", "Create Line", nullptr));
        actionCreate_Face->setText(QCoreApplication::translate("MainWindow", "Create_Surface", nullptr));
        actionMoveFeature->setText(QCoreApplication::translate("MainWindow", "Move", nullptr));
        actionRotateFeature->setText(QCoreApplication::translate("MainWindow", "Rotate", nullptr));
        actionRevol->setText(QCoreApplication::translate("MainWindow", "Revol", nullptr));
        actionLoft->setText(QCoreApplication::translate("MainWindow", "loft", nullptr));
        actionCreateDatumPlane->setText(QCoreApplication::translate("MainWindow", "Create Datum Plane", nullptr));
        actionDrawLine->setText(QCoreApplication::translate("MainWindow", "DrawLine", nullptr));
        actionDrawRectangle->setText(QCoreApplication::translate("MainWindow", "DrawRectangle", nullptr));
        actionDrawCircle->setText(QCoreApplication::translate("MainWindow", "DrawCircle", nullptr));
        actionCreate_Sketch->setText(QCoreApplication::translate("MainWindow", "Create Sketch", nullptr));
        actionDrawArc->setText(QCoreApplication::translate("MainWindow", "DrawArc", nullptr));
        actionDrawPolyline->setText(QCoreApplication::translate("MainWindow", "DrawPolyline", nullptr));
        actionMakeMatrix->setText(QCoreApplication::translate("MainWindow", "MakeMatrix", nullptr));
#if QT_CONFIG(tooltip)
        actionMakeMatrix->setToolTip(QCoreApplication::translate("MainWindow", "MakeMatrix", nullptr));
#endif // QT_CONFIG(tooltip)
        actionSweep->setText(QCoreApplication::translate("MainWindow", "Sweep", nullptr));
        actionDrawSpline->setText(QCoreApplication::translate("MainWindow", "DrawSpline", nullptr));
        actionDisplayPoint->setText(QCoreApplication::translate("MainWindow", "DisplayPoint", nullptr));
        actionDisplayCurve->setText(QCoreApplication::translate("MainWindow", "DisplayCurve", nullptr));
        actionDisplayFace->setText(QCoreApplication::translate("MainWindow", "DisplayFace", nullptr));
        actionSelectPoint->setText(QCoreApplication::translate("MainWindow", "SelectPoint", nullptr));
        actionSelectCurve->setText(QCoreApplication::translate("MainWindow", "SelectCurve", nullptr));
        actionSelectFace->setText(QCoreApplication::translate("MainWindow", "SelectFace", nullptr));
        actionSelectGeometryBody->setText(QCoreApplication::translate("MainWindow", "SelectGeometryBody", nullptr));
        actionPluginManager->setText(QCoreApplication::translate("MainWindow", "Plugin Manager", nullptr));
#if QT_CONFIG(tooltip)
        actionPluginManager->setToolTip(QCoreApplication::translate("MainWindow", "Plugin Manager", nullptr));
#endif // QT_CONFIG(tooltip)
        actionUser_Guidance->setText(QCoreApplication::translate("MainWindow", "User Guidance", nullptr));
        actionMeasure_Distance->setText(QCoreApplication::translate("MainWindow", "Measure Distance", nullptr));
        actionMeasure->setText(QCoreApplication::translate("MainWindow", "Measure", nullptr));
        actionGeoSplitter->setText(QCoreApplication::translate("MainWindow", "Split", nullptr));
        actionCreateGeoComponent->setText(QCoreApplication::translate("MainWindow", "CreateGeoComponent", nullptr));
        actionFluidMesh->setText(QCoreApplication::translate("MainWindow", "FluidMesh", nullptr));
        actionFilterMesh->setText(QCoreApplication::translate("MainWindow", "FilterMesh", nullptr));
        actionFillHole->setText(QCoreApplication::translate("MainWindow", "FillHole", nullptr));
        actionRemoveSurface->setText(QCoreApplication::translate("MainWindow", "RemoveSurface", nullptr));
        actionFillGap->setText(QCoreApplication::translate("MainWindow", "FillGap", nullptr));
        actionVTKTranslation->setText(QCoreApplication::translate("MainWindow", "Mesh Modeling", nullptr));
        FileToolBar->setWindowTitle(QCoreApplication::translate("MainWindow", "FileToolBar", nullptr));
        SolveToolBar->setWindowTitle(QCoreApplication::translate("MainWindow", "SolveToolBar", nullptr));
        ViewToolBar->setWindowTitle(QCoreApplication::translate("MainWindow", "ViewToolBar", nullptr));
        SelectToolBar->setWindowTitle(QCoreApplication::translate("MainWindow", "SelectToolBar", nullptr));
        MeshToolBar->setWindowTitle(QCoreApplication::translate("MainWindow", "MesherToolBar", nullptr));
        DisplayToolBar->setWindowTitle(QCoreApplication::translate("MainWindow", "DisplayToolBar", nullptr));
        SetToolBar->setWindowTitle(QCoreApplication::translate("MainWindow", "SetToolBar", nullptr));
        RedoToolBar->setWindowTitle(QCoreApplication::translate("MainWindow", "toolBar_4", nullptr));
        StartSketchToolBar->setWindowTitle(QCoreApplication::translate("MainWindow", "toolBar", nullptr));
        GeomertryFeatureToolBar->setWindowTitle(QCoreApplication::translate("MainWindow", "toolBar", nullptr));
        ChamferToolBar->setWindowTitle(QCoreApplication::translate("MainWindow", "toolBar_2", nullptr));
        BoolToolBar->setWindowTitle(QCoreApplication::translate("MainWindow", "toolBar_3", nullptr));
        FeatureOpertionToolBar->setWindowTitle(QCoreApplication::translate("MainWindow", "toolBar", nullptr));
        SketchToolBar->setWindowTitle(QCoreApplication::translate("MainWindow", "toolBar", nullptr));
        menuFile->setTitle(QCoreApplication::translate("MainWindow", "&File", nullptr));
        menuView->setTitle(QCoreApplication::translate("MainWindow", "&View", nullptr));
        menuHelp->setTitle(QCoreApplication::translate("MainWindow", "&Help", nullptr));
        menuSolve->setTitle(QCoreApplication::translate("MainWindow", "&Solve", nullptr));
        menuSettings->setTitle(QCoreApplication::translate("MainWindow", "&Settings", nullptr));
        menuLanguage->setTitle(QCoreApplication::translate("MainWindow", "Language", nullptr));
        menuMesher->setTitle(QCoreApplication::translate("MainWindow", "&Mesh", nullptr));
        menuView_2->setTitle(QCoreApplication::translate("MainWindow", "View", nullptr));
        menuSelect->setTitle(QCoreApplication::translate("MainWindow", "Select", nullptr));
        menuPost->setTitle(QCoreApplication::translate("MainWindow", "Post", nullptr));
        menuWindows->setTitle(QCoreApplication::translate("MainWindow", "Windows", nullptr));
        menuGeometry->setTitle(QCoreApplication::translate("MainWindow", "&Geometry", nullptr));
        menuFeature_Modeling->setTitle(QCoreApplication::translate("MainWindow", "Feature Modeling", nullptr));
        menuView_3->setTitle(QCoreApplication::translate("MainWindow", "View", nullptr));
        menuFeature_Operation->setTitle(QCoreApplication::translate("MainWindow", "Feature Operation", nullptr));
        menuSelect_2->setTitle(QCoreApplication::translate("MainWindow", "Select", nullptr));
        menuSketch->setTitle(QCoreApplication::translate("MainWindow", "Sketch", nullptr));
        menuPlugins->setTitle(QCoreApplication::translate("MainWindow", "Plugins", nullptr));
        MeasureToolBar->setWindowTitle(QCoreApplication::translate("MainWindow", "toolBar", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
